version: "3.8"
services:
    db:
        image: postgres:13-alpine
        ports:
            - 9432:5432
        container_name: db_gestmaint
        restart: always
        volumes:
            - db-data:/var/lib/
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: gestmaint
        networks:
            - dev

    adminer:
        image: adminer
        container_name: adminer_gestmaint
        restart: always
        environment:
            APP_ENV: dev
            ADMINER_DESIGN: pepa-linha
            ADMINER_DEFAULT_SERVER: db
        depends_on:
            - db
        ports:
            - 8080:8080
        networks:
            - dev
        
    maildev:
        image: maildev/maildev
        container_name: maildev_gestmaint
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8081:80"
        restart: always
        networks:
            - dev

    www:
        build: php
        container_name: www_gestmaint
        ports:
            - "9000:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: